# path to database sheet (TSV format, columns: database_name, path_db)
databases: config/databases.tsv

# path to contigs folder
contigs: /home/rdenise/Documents/scripts/virome_pipeline/myfiles/contigs

contigs_ext: fasta.gz

# name of the project 
project_name: your_project_name_dag

# path to the result folder
output_folder: results

# Blast option if not given in seeds.tsv
default_blast_option:
    # E-value threshold: if you want to use scientific notation put a dot after the first number (e.g. 1.e-10 not 1e-10)
    e_val: 1.e-10
    # coverage of the contig (between 0 and 1)
    coverage: 0.7

# Blast option if not given in seeds.tsv
default_hmmer_option:
    # E-value threshold for the full sequence: if you want to use scientific notation put a dot after the first number (e.g. 1.e-10 not 1e-10)
    e_val_full: 1.e-3
    # E-value threshold for per domain: if you want to use scientific notation put a dot after the first number (e.g. 1.e-10 not 1e-10)
    e_val_dom: 0.1


# Default value for plot
default_values_plot:
    # Color
    color: '#131516' # This color is a dark grey similar to black
    # Turn color of the border a darker shade infer from the background if True else set the color to black
    colored_border: True
    # Turn border to roundish shape
    round_border: False

# Default option for prokka
default_prokka_option:
    # protein database
    protein_db: /home/rdenise/Documents/scripts/virome_pipeline/myfiles/databases/viral_proteins_plus_crass.fa
    # hmm database:
    hmm_db: /home/rdenise/Documents/scripts/virome_pipeline/myfiles/databases/pVOGs/all_vogs.hmm
    # Annotation mode: Archaea|Bacteria|Mitochondria|Viruses (default 'Viruses')
    kingdom: Viruses

# Default option for deepvirfinder
default_deepvirfinder_option:
    # predict only for sequence >= L bp
    cutoff_length: 1000

# Default option for virsorter
default_virsorter_option:
    # predict only for sequence >= L bp
    cutoff_length: 5000

# Default option for DRAMv
default_dramv_option:
    # predict only for sequence >= L bp
    cutoff_length: 1000
