$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  project_name:
    type: string
  output_folder:
    type: string
  databases:
    type: string
  annotation_phages:
    type: string
  annotation_proteins:
    type: string
  contigs:
    type: string
  contigs_ext:
    type: string
  contigs_reads:
    type: string
  default_blast_option:
    type: object
    properties:
      e_val:
        type: number
        minimum: 0
        maximum: 1
      coverage:
        type: number
        minimum: 0
        maximum: 1    
      pident:
        type: number
        minimum: 0
        maximum: 1 
      cov_min:
        type: string
        enum: ["mean","subject", "query", "shortest", "longest"]
      pid_min:
        type: string
        enum: ["mean","subject", "query", "shortest", "longest", "HSP"]
      length_min:
        type: number
    required:
      - cov_min
      - pid_min
      - length_min
      - e_val
      - coverage

  iphop_db:
    type: string

  default_hmmer_option:
    type: object
    properties:
      e_val_full:
        type: number
        minimum: 0
        maximum: 1
      coverage:
        type: number
        minimum: 0
        maximum: 1    
    required:
      - e_val_full
      - e_val_dom

  default_values_plot:
    type: object
    properties:
      color:
        type: string
      colored_border:
        type: boolean
      round_border:
        type: boolean
 
  default_prokka_option:
    type: object
    properties:
      protein_db:
        type: string
      hmm_db:
        type: string
      kingdom:
        type: string

  default_deepvirfinder_option:
    type: object
    properties:
      cutoff_length:
        type: number
        minimum: 1

  default_virsorter_option:
    type: object
    properties:
      cutoff_length:
        type: number
        minimum: 1

  default_dramv_option:
    type: object
    properties:
      cutoff_length:
        type: number
        minimum: 1        

required:
  - databases
  - contigs
  - contigs_ext
  - project_name
  - output_folder
  - default_blast_option
  - default_prokka_option
  - default_deepvirfinder_option
  - default_virsorter_option
  - default_dramv_option
  - contigs_reads
  - iphop_db